"""add user weights and reset tokens

Revision ID: d1973301750c
Revises: cee9e990c887
Create Date: 2026-08-06 18:44:08.033387
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd1973301750c'
down_revision: Union[str, None] = 'cee9e990c887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_weights', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('verify_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reset_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reset_expires', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_reset_token'), ['reset_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_verify_token'), ['verify_token'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_verify_token'))
        batch_op.drop_index(batch_op.f('ix_users_reset_token'))
        batch_op.drop_column('reset_expires')
        batch_op.drop_column('reset_token')
        batch_op.drop_column('verify_token')
        batch_op.drop_column('score_weights')

    # ### end Alembic commands ###
